# Generated by Django 2.1.1 on 2018-12-12 02:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181211_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
